// Gate-driven ADSR envelope used by the tone editor and the FPGA voice.
// Behaviour matches the essential Vital-style rule:
//   gate high  -> Attack, Decay, then remain at Sustain
//   gate low   -> immediately Release from the current level
// Curve values are 256-point Q0.16 progress LUTs generated by the editor.
module adsr_envelope (
    input  wire        clk,
    input  wire        reset_n,
    input  wire        sample_tick,
    input  wire        gate,
    // Runtime-configurable timing.  The UART controller updates these
    // registers; samples and phase increments must be written as a pair.
    input  wire [31:0] attack_samples,
    input  wire [31:0] attack_phase_inc,
    input  wire [31:0] decay_samples,
    input  wire [31:0] decay_phase_inc,
    input  wire [15:0] sustain_level,
    input  wire [31:0] release_samples,
    input  wire [31:0] release_phase_inc,
    input  wire [15:0] attack_curve_value,
    input  wire [15:0] decay_curve_value,
    input  wire [15:0] release_curve_value,
    output wire [7:0]  curve_address,
    output reg  [15:0] level
);

    localparam [2:0] ENV_IDLE    = 3'd0;
    localparam [2:0] ENV_ATTACK  = 3'd1;
    localparam [2:0] ENV_DECAY   = 3'd2;
    localparam [2:0] ENV_SUSTAIN = 3'd3;
    localparam [2:0] ENV_RELEASE = 3'd4;

    reg [2:0]  state;
    reg [31:0] stage_count;
    reg [31:0] stage_phase;
    reg [15:0] stage_start_level;

    wire [16:0] attack_range = 17'd65535 - {1'b0, stage_start_level};
    wire [32:0] attack_product = attack_range * attack_curve_value;
    wire [17:0] attack_level_wide = {2'b00, stage_start_level} + {1'b0, attack_product[32:16]};
    wire [16:0] attack_level = attack_level_wide[16:0];

    wire [16:0] decay_range = 17'd65535 - {1'b0, sustain_level};
    wire [32:0] decay_product = decay_range * decay_curve_value;
    wire [17:0] decay_level_wide = 18'd65535 - {1'b0, decay_product[32:16]};
    wire [16:0] decay_level = decay_level_wide[16:0];

    wire [15:0] release_remaining = 16'hFFFF - release_curve_value;
    wire [31:0] release_product = stage_start_level * release_remaining;
    wire [15:0] release_level = release_product >> 16;

    assign curve_address = stage_phase[31:24];

    function [31:0] saturated_phase_add;
        input [31:0] value;
        input [31:0] increment;
        begin
            if (value > (32'hFFFFFFFF - increment))
                saturated_phase_add = 32'hFFFFFFFF;
            else
                saturated_phase_add = value + increment;
        end
    endfunction

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            state             <= ENV_IDLE;
            stage_count       <= 32'd0;
            stage_phase       <= 32'd0;
            stage_start_level <= 16'd0;
            level             <= 16'd0;
        end else if (sample_tick) begin
            case (state)
                ENV_IDLE: begin
                    level       <= 16'd0;
                    stage_count <= 32'd0;
                    stage_phase <= 32'd0;
                    if (gate) begin
                        stage_start_level <= 16'd0;
                        state <= ENV_ATTACK;
                    end
                end

                ENV_ATTACK: begin
                    if (!gate) begin
                        state             <= ENV_RELEASE;
                        stage_start_level <= level;
                        stage_count       <= 32'd0;
                        stage_phase       <= 32'd0;
                    end else if (stage_count >= attack_samples - 1) begin
                        level       <= 16'hFFFF;
                        stage_count <= 32'd0;
                        stage_phase <= 32'd0;
                        state       <= ENV_DECAY;
                    end else if (stage_count == 0) begin
                        // Synchronous curve ROM needs one sample to return
                        // address zero. Keep the exact retrigger level meanwhile.
                        level       <= stage_start_level;
                        stage_count <= 32'd1;
                        stage_phase <= saturated_phase_add(stage_phase, attack_phase_inc);
                    end else begin
                        level       <= attack_level[15:0];
                        stage_count <= stage_count + 1'b1;
                        stage_phase <= saturated_phase_add(stage_phase, attack_phase_inc);
                    end
                end

                ENV_DECAY: begin
                    if (!gate) begin
                        state             <= ENV_RELEASE;
                        stage_start_level <= level;
                        stage_count       <= 32'd0;
                        stage_phase       <= 32'd0;
                    end else if (stage_count >= decay_samples - 1) begin
                        level       <= sustain_level;
                        state       <= ENV_SUSTAIN;
                        stage_count <= 32'd0;
                        stage_phase <= 32'd0;
                    end else if (stage_count == 0) begin
                        level       <= 16'hFFFF;
                        stage_count <= 32'd1;
                        stage_phase <= saturated_phase_add(stage_phase, decay_phase_inc);
                    end else begin
                        level       <= decay_level[15:0];
                        stage_count <= stage_count + 1'b1;
                        stage_phase <= saturated_phase_add(stage_phase, decay_phase_inc);
                    end
                end

                ENV_SUSTAIN: begin
                    level <= sustain_level;
                    if (!gate) begin
                        state             <= ENV_RELEASE;
                        stage_start_level <= sustain_level;
                        stage_count       <= 32'd0;
                        stage_phase       <= 32'd0;
                    end
                end

                ENV_RELEASE: begin
                    if (gate) begin
                        state             <= ENV_ATTACK;
                        stage_start_level <= level;
                        stage_count       <= 32'd0;
                        stage_phase       <= 32'd0;
                    end else if (stage_count >= release_samples - 1) begin
                        level       <= 16'd0;
                        state       <= ENV_IDLE;
                        stage_count <= 32'd0;
                        stage_phase <= 32'd0;
                    end else if (stage_count == 0) begin
                        level       <= stage_start_level;
                        stage_count <= 32'd1;
                        stage_phase <= saturated_phase_add(stage_phase, release_phase_inc);
                    end else begin
                        level       <= release_level;
                        stage_count <= stage_count + 1'b1;
                        stage_phase <= saturated_phase_add(stage_phase, release_phase_inc);
                    end
                end

                default: begin
                    state <= ENV_IDLE;
                    level <= 16'd0;
                end
            endcase
        end
    end

endmodule
