import json
import re
from pathlib import Path

import numpy as np

from tone_model import (
    SAMPLE_RATE,
    WAVETABLE_POINTS,
    cutoff_to_lut_index,
    filter_alpha_lut,
)


def _safe_stem(name):
    aliases = {
        "钢琴": "piano", "小提琴": "violin", "管弦弦乐": "orchestral_strings",
        "铜管": "brass", "管风琴": "organ", "长笛": "flute",
    }
    for label, alias in aliases.items():
        if label in name:
            return alias
    stem = re.sub(r"[^0-9A-Za-z_\-]+", "_", name).strip("_")
    return stem or "tone"


def _write_mem(path, values, width=16):
    digits = (width + 3) // 4
    mask = (1 << width) - 1
    lines = [format(int(value) & mask, "0{}X".format(digits)) for value in values]
    Path(path).write_text("\n".join(lines) + "\n", encoding="ascii")


def _ms_to_samples(milliseconds):
    value = int(round(float(milliseconds) * SAMPLE_RATE / 1000.0))
    return max(1, value)


def _stage_phase_increment(samples):
    if samples <= 1:
        return 0xFFFFFFFF
    return min(0xFFFFFFFF, int(round(0xFFFFFFFF / float(samples - 1))))


def _curve_lut(curve):
    progress = np.linspace(0.0, 1.0, 256, dtype=np.float64)
    exponent = 2.0 ** (-2.0 * max(-1.0, min(1.0, float(curve))))
    shaped = np.power(progress, exponent)
    return np.rint(shaped * 65535.0).clip(0, 65535).astype(np.uint16)


def _envelope_values(prefix, envelope):
    attack = _ms_to_samples(envelope.attack_ms)
    decay = _ms_to_samples(envelope.decay_ms)
    release = _ms_to_samples(envelope.release_ms)
    sustain = int(round(max(0.0, min(1.0, envelope.sustain)) * 65535.0))
    return [
        "`define TONE_{}_ATTACK_SAMPLES 32'd{}".format(prefix, attack),
        "`define TONE_{}_ATTACK_PHASE_INC 32'h{:08X}".format(prefix, _stage_phase_increment(attack)),
        "`define TONE_{}_DECAY_SAMPLES 32'd{}".format(prefix, decay),
        "`define TONE_{}_DECAY_PHASE_INC 32'h{:08X}".format(prefix, _stage_phase_increment(decay)),
        "`define TONE_{}_SUSTAIN_Q16 16'd{}".format(prefix, sustain),
        "`define TONE_{}_RELEASE_SAMPLES 32'd{}".format(prefix, release),
        "`define TONE_{}_RELEASE_PHASE_INC 32'h{:08X}".format(prefix, _stage_phase_increment(release)),
    ]


def _write_bundle(tone, output, names, memory_references):
    output.mkdir(parents=True, exist_ok=True)
    paths = {key: output / filename for key, filename in names.items()}

    _write_mem(paths["wavetable"], tone.wavetable, 16)
    _, alpha_lut = filter_alpha_lut()
    _write_mem(paths["filter_alpha_lut"], alpha_lut, 16)

    envelopes = {
        "amp": tone.amplitude_envelope,
        "filter": tone.filter.envelope,
    }
    for prefix, envelope in envelopes.items():
        _write_mem(paths[prefix + "_attack_curve"], _curve_lut(envelope.attack_curve), 16)
        _write_mem(paths[prefix + "_decay_curve"], _curve_lut(envelope.decay_curve), 16)
        _write_mem(paths[prefix + "_release_curve"], _curve_lut(envelope.release_curve), 16)

    min_idx = cutoff_to_lut_index(tone.filter.min_cutoff_hz)
    max_idx = cutoff_to_lut_index(tone.filter.max_cutoff_hz)
    gain_q15 = int(round(max(0.0, min(1.0, tone.master_gain)) * 32767.0))
    filter_amount_q16 = int(round(max(0.0, min(1.0, tone.filter.envelope_amount)) * 65535.0))
    c4_phase_increment = int(round(261.625565 * (2 ** 32) / SAMPLE_RATE))

    defines = [
        "// Generated by Gowin Tone Designer. Re-deploy from the editor instead of editing this file.",
        "`ifndef GOWIN_TONE_PARAMS_VH",
        "`define GOWIN_TONE_PARAMS_VH",
        "`define TONE_WAVETABLE_POINTS {}".format(WAVETABLE_POINTS),
        "`define TONE_SAMPLE_RATE_HZ {}".format(int(round(SAMPLE_RATE))),
        "`define TONE_DEFAULT_PHASE_INC 32'd{}".format(c4_phase_increment),
    ]
    defines.extend(_envelope_values("AMP", tone.amplitude_envelope))
    defines.extend(_envelope_values("FILTER", tone.filter.envelope))
    defines.extend([
        "`define TONE_MASTER_GAIN_Q15 16'd{}".format(gain_q15),
        "`define TONE_FILTER_ENABLE 1'b{}".format(1 if tone.filter.enabled else 0),
        "`define TONE_FILTER_FOLLOW_AMP 1'b{}".format(1 if tone.filter.follow_amplitude_envelope else 0),
        "`define TONE_FILTER_MIN_INDEX 8'd{}".format(min_idx),
        "`define TONE_FILTER_MAX_INDEX 8'd{}".format(max_idx),
        "`define TONE_FILTER_AMOUNT_Q16 16'd{}".format(filter_amount_q16),
        "`define TONE_WAVETABLE_MEM \"{}\"".format(memory_references["wavetable"]),
        "`define TONE_FILTER_LUT_MEM \"{}\"".format(memory_references["filter_alpha_lut"]),
        "`define TONE_AMP_ATTACK_CURVE_MEM \"{}\"".format(memory_references["amp_attack_curve"]),
        "`define TONE_AMP_DECAY_CURVE_MEM \"{}\"".format(memory_references["amp_decay_curve"]),
        "`define TONE_AMP_RELEASE_CURVE_MEM \"{}\"".format(memory_references["amp_release_curve"]),
        "`define TONE_FILTER_ATTACK_CURVE_MEM \"{}\"".format(memory_references["filter_attack_curve"]),
        "`define TONE_FILTER_DECAY_CURVE_MEM \"{}\"".format(memory_references["filter_decay_curve"]),
        "`define TONE_FILTER_RELEASE_CURVE_MEM \"{}\"".format(memory_references["filter_release_curve"]),
        "`endif",
        "",
    ])
    paths["params"].write_text("\n".join(defines), encoding="utf-8")

    manifest = {
        "format": "gowin-fpga-tone-export-v2",
        "tone_name": tone.name,
        "sample_rate_hz": SAMPLE_RATE,
        "wavetable_points": WAVETABLE_POINTS,
        "wavetable_format": "signed-q1.15-two-complement-hex",
        "envelope_logic": "gate-driven-attack-decay-sustain-release",
        "curve_lut_format": "unsigned-q0.16-hex-256-points",
        "filter_coefficient_format": "unsigned-q0.16-hex",
        "files": {key: path.name for key, path in paths.items()},
    }
    paths["manifest"].write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    ordered_keys = [
        "wavetable", "filter_alpha_lut", "params", "manifest",
        "amp_attack_curve", "amp_decay_curve", "amp_release_curve",
        "filter_attack_curve", "filter_decay_curve", "filter_release_curve",
    ]
    return [paths[key] for key in ordered_keys]


def _bundle_names(stem="tone"):
    return {
        "wavetable": stem + "_wavetable.mem",
        "filter_alpha_lut": "filter_alpha_lut.mem",
        "params": stem + "_params.vh",
        "manifest": stem + "_fpga_manifest.json",
        "amp_attack_curve": stem + "_amp_attack_curve.mem",
        "amp_decay_curve": stem + "_amp_decay_curve.mem",
        "amp_release_curve": stem + "_amp_release_curve.mem",
        "filter_attack_curve": stem + "_filter_attack_curve.mem",
        "filter_decay_curve": stem + "_filter_decay_curve.mem",
        "filter_release_curve": stem + "_filter_release_curve.mem",
    }


def export_tone(tone, output_directory):
    tone.ensure_valid()
    output = Path(output_directory)
    names = _bundle_names(_safe_stem(tone.name))
    references = {key: filename for key, filename in names.items() if key.endswith("curve")}
    references["wavetable"] = names["wavetable"]
    references["filter_alpha_lut"] = names["filter_alpha_lut"]
    return _write_bundle(tone, output, names, references)


def export_tone_to_fpga_project(tone, project_directory):
    tone.ensure_valid()
    project = Path(project_directory)
    if not (project / "fpga_project.gprj").is_file():
        raise FileNotFoundError("fpga_project.gprj not found in {}".format(project))
    output = project / "src" / "generated"
    names = _bundle_names("tone")
    references = {
        key: "src/generated/{}".format(filename)
        for key, filename in names.items()
        if key == "wavetable" or key == "filter_alpha_lut" or key.endswith("curve")
    }
    return _write_bundle(tone, output, names, references)
